services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__gifteee=Host=postgres;Port=5432;Database=gifteee;Username=gifteee;Password=gifteee

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: gifteee
      POSTGRES_USER: gifteee
      POSTGRES_PASSWORD: gifteee
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: